set nocompatible

syntax on
set relativenumber
set number
set tabstop=4
set shiftwidth=4
set autoread
set hlsearch
set incsearch
set undofile
set smartindent
set cursorline
set ttimeoutlen=50
set laststatus=2
set signcolumn=yes
set path=.,,
set colorcolumn=80,88,120
set background=dark
set foldmethod=indent
set foldlevel=100
set foldlevelstart=101
set nowildmenu
set wildmode=list:longest,full
set mouse=a

let g:netrw_bufsettings = "noma nomod nu rnu ro nobl"

nnoremap <C-L> <cmd>nohlsearch<bar>diffupdate<bar>normal! <C-L><CR>
nnoremap - <cmd>Explore<cr>
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
cnoremap <M-b> <S-Left>
cnoremap <M-f> <S-Right>

colo lunaperche
