hi! link typescriptMember Normal
hi! link typescriptObjectLabel Normal
hi! link typescriptTypeReference Normal
hi! link typescriptVariable Statement
hi! link typescriptEnumKeyword Statement
hi! link typescriptAssign Operator
hi! link typescriptOperator Operator
hi! link typescriptObjectColon Operator
hi! link typescriptTypeAnnotation Operator
