return {
	{ "Mofiqul/dracula.nvim" },
	{ "sainnhe/gruvbox-material" },
	{ "ellisonleao/gruvbox.nvim" },
	{ "rose-pine/neovim", name = "rose-pine" },
	{ "scottmckendry/cyberdream.nvim" },
	{ "sainnhe/sonokai" },
	{ "tanvirtin/monokai.nvim" },
	{ "catppuccin/nvim", name = "catppuccin" },
	{ "ribru17/bamboo.nvim" },
	{ "rebelot/kanagawa.nvim" },
	{ "EdenEast/nightfox.nvim" },
	{ "navarasu/onedark.nvim" },
	{ "miikanissi/modus-themes.nvim" },
	{ "tiagovla/tokyodark.nvim" },
	{ "folke/tokyonight.nvim", priority = 1000, lazy = false },
	{ "0xstepit/flow.nvim" },
}
