return {
	-- { "Mofiqul/dracula.nvim" },
	-- { "sainnhe/gruvbox-material" },
	{ "ellisonleao/gruvbox.nvim", priority = 1000, config = true, opts = ... },
	-- { "rose-pine/neovim", name = "rose-pine" },
	{ "scottmckendry/cyberdream.nvim" },
	-- { "sainnhe/sonokai" },
	-- { "tanvirtin/monokai.nvim" },
	-- { "shaunsingh/solarized.nvim" },
	-- { "sainnhe/edge" },
	-- { "catppuccin/nvim", name = "catppuccin" },
	-- { "ribru17/bamboo.nvim" },
	{ "rebelot/kanagawa.nvim" },
	{ "AlexvZyl/nordic.nvim" },
	-- { "savq/melange-nvim" },
	-- { "shaunsingh/nord.nvim" },
	-- { "ray-x/aurora" },
	-- { "EdenEast/nightfox.nvim" },
	-- { "miikanissi/modus-themes.nvim" },
	-- { "tiagovla/tokyodark.nvim" },
	{ "folke/tokyonight.nvim" },
	-- {
	-- 	"0xstepit/flow.nvim",
	-- 	config = function()
	-- 		require("flow").setup({
	-- 			mode = "desaturate",
	-- 		})
	-- 	end,
	-- },
	-- { "neanias/everforest-nvim" },
	-- { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = false, priority = 1000 },
	-- { "glepnir/zephyr-nvim" },
	-- { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = false, priority = 1000 },
	-- { "rmehri01/onenord.nvim" },
	-- { "eldritch-theme/eldritch.nvim", lazy = false, priority = 1000 },
	-- { "lewpoly/sherbet.nvim" },
	{ "zootedb0t/citruszest.nvim", lazy = false, priority = 1000 },
	{ "mhartington/oceanic-next", lazy = false, priority = 1000 },
	-- { "kaiuri/nvim-juliana", lazy = false },
	-- { "cpea2506/one_monokai.nvim" },
	-- {
	-- 	"rockyzhang24/arctic.nvim",
	-- 	dependencies = { "rktjmp/lush.nvim" },
	-- 	name = "arctic",
	-- 	branch = "main",
	-- 	priority = 1000,
	-- },
	-- { "NLKNguyen/papercolor-theme" },
	-- { "Yazeed1s/minimal.nvim" },
	{ "uloco/bluloco.nvim", dependencies = { "rktjmp/lush.nvim" }, lazy = false, priority = 1000 },
	-- { "tersetears/maani.nvim", dependencies = { "rktjmp/lush.nvim" }, lazy = false, priority = 1000 },
	{ "pineapplegiant/spaceduck", branch = "main" },
	-- { "iagorrr/noctishc.nvim" },
	{ "metalelf0/jellybeans-nvim", dependencies = { "rktjmp/lush.nvim" }, lazy = false, priority = 1000 },
	-- { "samharju/synthweave.nvim" },
	-- { "Tsuzat/NeoSolarized.nvim" },
	-- {
	-- 	"sekke276/dark_flat.nvim",
	-- 	dependencies = { "rktjmp/lush.nvim" },
	-- 	lazy = false,
	-- 	priority = 1000,
	-- },
	-- { "agude/vim-eldar" },
	{ "bignimbus/pop-punk.vim", lazy = false, priority = 1000 },
	-- { "itchyny/landscape.vim" },
	-- {
	-- 	"olimorris/onedarkpro.nvim",
	-- 	priority = 1000, -- Ensure it loads first
	-- },
	{
		"navarasu/onedark.nvim",
		lazy = false,
		priority = 1000,
		config = function()
			require("onedark").setup({
				style = "deep",
			})
		end,
	},
	-- { "ttak0422/morimo" },
	-- { "shawilly/ponokai", lazy = false, priority = 1000 },
	-- { "blackbirdtheme/vim" },
	-- { "jsit/toast.vim" },
}
