# ZSH OPTIONS

source ~/.fzf-tab/fzf-tab.plugin.zsh
autoload -Uz compinit && compinit
autoload -U bashcompinit && bashcompinit

bindkey -e

autoload -Uz pushd
setopt auto_pushd
setopt prompt_subst
setopt share_history
setopt hist_ignore_dups
setopt pushd_ignore_dups
setopt auto_cd

# ZLE WIDGETS

jobs_widget() {
	echo ""
	jobs
	zle reset-prompt
}
fg_plus_widget() {
	zle -I
	fg %+
	zle -I
}
fg_minus_widget() {
	zle -I
	fg %-
	zle -I
}
kill_job_plus_widget() { kill %+ && fg %+; }
kill_job_minus_widget() { kill %+ && fg %+; }
zle -N jobs_widget
zle -N fg_plus_widget
zle -N fg_minus_widget
zle -N kill_job_plus_widget
zle -N kill_job_minus_widget
for i in {1..9}; do
	eval "fg_${i}_widget() { zle -I; fg %${i}; zle -I; }"
	eval "kill_job_${i}_widget() { kill %${i} && fg %${i}; }"
	eval "zle -N fg_${i}_widget"
	eval "zle -N kill_job_${i}_widget"
done

# ZSH KEYMAPS

bindkey '^J^J' jobs_widget
bindkey '^Jj' jobs_widget
bindkey '^I' expand-or-complete
bindkey '^]' fzf-tab-complete
bindkey '^U' backward-kill-line
bindkey '^[[Z' reverse-menu-complete
bindkey '^J^M' fg_plus_widget
bindkey '^Jm' fg_plus_widget
bindkey '^J^N' fg_minus_widget
bindkey '^Jn' fg_minus_widget
bindkey '^J^K^M' kill_job_plus_widget
bindkey '^J^Km' kill_job_plus_widget
bindkey '^J^K^N' kill_job_minus_widget
bindkey '^J^Kn' kill_job_minus_widget
for i in {1..9}; do
	eval "bindkey '^J${i}' fg_${i}_widget"
	eval "bindkey '^J^K${i}' kill_job_${i}_widget"
done

# ALIASES

alias soz="source ~/.zshrc"
alias sov="source venv/bin/activate || source .venv/bin/activate"

alias mux="cd && ~/dotfiles/tmux/tmux-session.sh"
alias nvs="nvim -S Session.vim"
alias vs="vim -S Session.vim"
alias nvcd="nvim -c 'cd %:h'"
alias nvco='nvim -c "CopilotChatOpen" -c "wincmd o" -c "startinsert"'
alias nvz="nvim -c 'cd' ~/.zshrc"
alias nvd="nvim -c 'cd %:h' ~/dotfiles"

alias k="kubectl"
alias kn="k config set-context --current --namespace"
alias kx="k config use-context"
alias kl="k config get-contexts | sed -E 's/(^\*.*)/\x1b\[7m\1\x1b\[0m/'"

alias ga="gcloud auth login --update-adc"
alias co="copilot"
alias jq="jq --indent 4"
alias bd=". bd -si"

# FUNCTIONS

difftool() {
	nvim -c "let g:taboo_tab_format = \" %N %R \"" -c "Git difftool -y $1" \
		-c "set showtabline=2" -c "set tabclose=" -c "exe 'cd ' .. getcwd()" \
		-c "1tabcl"
}

ghclone() {
	git clone "https://github.com/$1.git"
}

# VARS

PROMPT='%F{blue}%0~%f ${vcs_info_msg_0_}%F{green}%(!.#.>) %f'
HISTSIZE=9999
SAVEHIST=9999
KEYTIMEOUT=200

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR=nvim
export BINDIR="$HOME/.local/bin"
export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacadah
export GIT_PAGER="diff-highlight | less"
export FZF_DEFAULT_OPTS="--bind ctrl-b:half-page-up,ctrl-f:half-page-down"

if command -v bat >/dev/null 2>&1; then
	alias less="bat"
	export BAT_STYLE=grid
	export MANPAGER=bat
fi

source <(fzf --zsh)
fpath=(~/.zsh/completion $fpath)

export TERM="xterm-256color"
[[ -n $TMUX ]] && export TERM="screen-256color"
