bindkey -e

bindkey '^U' backward-kill-line
bindkey '^[[Z' reverse-menu-complete
autoload -U +X bashcompinit && bashcompinit
autoload -Uz pushd

setopt auto_pushd
setopt prompt_subst
setopt share_history
setopt hist_ignore_dups
setopt pushd_ignore_dups
setopt auto_cd

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats '%F{yellow}(%f%F{red}%b%f%F{yellow})%u%c%m %f'
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
+vi-git-untracked() {
	if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == 'true' ]] &&
		git status --porcelain | grep -m 1 '^??' &>/dev/null; then
		hook_com[misc]='?'
	fi
}
precmd() {
	vcs_info
}

PROMPT='%F{blue}%0~%f ${vcs_info_msg_0_}%F{green}%(!.#.>) %f'
HISTSIZE=100000
SAVEHIST=100000

export PATH="$PATH:$HOME/.local/bin"
export EDITOR=nvim
export BINDIR="$HOME/.local/bin"
export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacadah
export GIT_PAGER="diff-highlight | less"
export FZF_DEFAULT_OPTS="--bind ctrl-b:half-page-up,ctrl-f:half-page-down"

if command -v bat >/dev/null 2>&1; then
	alias less="bat"
	export BAT_STYLE=grid
	export MANPAGER=bat
fi

alias soz="source ~/.zshrc"
alias sov="source venv/bin/activate || source .venv/bin/activate"

alias mux="cd && ~/dotfiles/tmux/tmux-session.sh"
alias nvs="nvim -S Session.vim"
alias vs="vim -S Session.vim"
alias nvco='nvim -c "CopilotChatOpen" -c "wincmd o" -c "startinsert"'
alias nvz='nvim ~/.zshrc'

alias k="kubectl"
alias kn="k config set-context --current --namespace"
alias kx="k config use-context"
alias kl="k config get-contexts"

alias ga="gcloud auth login --update-adc"
alias co="copilot"
alias jq="jq --indent 4"
alias bd=". bd -si"

difftool() {
	nvim -c "let g:taboo_tab_format = \" %N %R \"" -c "Git difftool -y $1" \
		-c "set showtabline=2" -c "set tabclose=" -c "exe 'cd ' .. getcwd()" \
		-c "1tabcl"
}

ghclone() {
	git clone "https://github.com/$1.git"
}

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

source <(fzf --zsh)
fpath=(~/.zsh/completion $fpath)

export TERM="xterm-256color"
[[ -n $TMUX ]] && export TERM="screen-256color"

source ~/.fzf-tab/fzf-tab.plugin.zsh
bindkey "^I" expand-or-complete
bindkey '^]' fzf-tab-complete
